name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml
    with:
      install_command_linux: 'python -m pip install -e ".[dev,all]"'
      install_command_macos: >-
        python -m pip install -e ".[dev,biocpy,parquet,anndata,pybiocfilecache]"
      install_command_windows: >-
        python -m pip install -e ".[dev,parquet,pybiocfilecache]"

  coverage:
    uses: ./.github/workflows/report-coverage.yml
    secrets: inherit
