name: Publish package

on:
  workflow_call:
    inputs:
      repository_url:
        description: Upload endpoint URL of the target PyPI index.
        required: true
        type: string
    secrets:
      PYPI_API_TOKEN:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Build package
        run: |
          python3 -m pip install --upgrade pip build
          python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: ${{ inputs.repository_url }}
          skip-existing: true
